use std::fmt::{Debug, Formatter};

pub enum Tag {
    A,
    ABBR,
    ACRONYM,
    ADDRESS,
    APPLET,
    AREA,
    ARTICLE,
    ASIDE,
    AUDIO,
    B,
    BASE,
    BASEFONT,
    BDI,
    BDO,
    BGSOUND,
    BIG,
    BLINK,
    BLOCKQUOTE,
    BODY,
    BR,
    BUTTON,
    CANVAS,
    CAPTION,
    CENTER,
    CITE,
    CODE,
    COL,
    COLGROUP,
    CONTENT,
    DATA,
    DATALIST,
    DD,
    DECORATOR,
    DEL,
    DETAILS,
    DFN,
    DIR,
    DIV,
    DL,
    DT,
    ELEMENT,
    EM,
    EMBED,
    FIELDSET,
    FIGCAPTION,
    FIGURE,
    FONT,
    FOOTER,
    FORM,
    FRAME,
    FRAMESET,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    HEAD,
    HEADER,
    HGROUP,
    HR,
    HTML,
    I,
    IFRAME,
    IMG,
    INPUT,
    INS,
    ISINDEX,
    KBD,
    KEYGEN,
    LABEL,
    LEGEND,
    LI,
    LINK,
    LISTING,
    MAIN,
    MAP,
    MARK,
    MARQUEE,
    MENU,
    MENUITEM,
    META,
    METER,
    NAV,
    NOBR,
    NOFRAMES,
    NOSCRIPT,
    OBJECT,
    OL,
    OPTGROUP,
    OPTION,
    OUTPUT,
    P,
    PARAM,
    PLAINTEXT,
    PRE,
    PROGRESS,
    Q,
    RP,
    RT,
    RUBY,
    S,
    SAMP,
    SCRIPT,
    SECTION,
    SELECT,
    SHADOW,
    SMALL,
    SOURCE,
    SPACER,
    SPAN,
    STRIKE,
    STRONG,
    STYLE,
    SUB,
    SUMMARY,
    SUP,
    TABLE,
    TBODY,
    TD,
    TEMPLATE,
    TEXTAREA,
    TFOOT,
    TH,
    THEAD,
    TIME,
    TITLE,
    TR,
    TRACK,
    TT,
    U,
    UL,
    VAR,
    VIDEO,
    WBR,
    XMP,
}

impl Tag {
    pub fn from_str(s: &str) -> Option<Tag> {
        match s {
            "a" => Some(Tag::A),
            "abbr" => Some(Tag::ABBR),
            "acronym" => Some(Tag::ACRONYM),
            "address" => Some(Tag::ADDRESS),
            "applet" => Some(Tag::APPLET),
            "area" => Some(Tag::AREA),
            "article" => Some(Tag::ARTICLE),
            "aside" => Some(Tag::ASIDE),
            "audio" => Some(Tag::AUDIO),
            "b" => Some(Tag::B),
            "base" => Some(Tag::BASE),
            "basefont" => Some(Tag::BASEFONT),
            "bdi" => Some(Tag::BDI),
            "bdo" => Some(Tag::BDO),
            "bgsound" => Some(Tag::BGSOUND),
            "big" => Some(Tag::BIG),
            "blink" => Some(Tag::BLINK),
            "blockquote" => Some(Tag::BLOCKQUOTE),
            "body" => Some(Tag::BODY),
            "br" => Some(Tag::BR),
            "button" => Some(Tag::BUTTON),
            "canvas" => Some(Tag::CANVAS),
            "caption" => Some(Tag::CAPTION),
            "center" => Some(Tag::CENTER),
            "cite" => Some(Tag::CITE),
            "code" => Some(Tag::CODE),
            "col" => Some(Tag::COL),
            "colgroup" => Some(Tag::COLGROUP),
            "content" => Some(Tag::CONTENT),
            "data" => Some(Tag::DATA),
            "datalist" => Some(Tag::DATALIST),
            "dd" => Some(Tag::DD),
            "decorator" => Some(Tag::DECORATOR),
            "del" => Some(Tag::DEL),
            "details" => Some(Tag::DETAILS),
            "dfn" => Some(Tag::DFN),
            "dir" => Some(Tag::DIR),
            "div" => Some(Tag::DIV),
            "dl" => Some(Tag::DL),
            "dt" => Some(Tag::DT),
            "element" => Some(Tag::ELEMENT),
            "em" => Some(Tag::EM),
            "embed" => Some(Tag::EMBED),
            "fieldset" => Some(Tag::FIELDSET),
            "figcaption" => Some(Tag::FIGCAPTION),
            "figure" => Some(Tag::FIGURE),
            "font" => Some(Tag::FONT),
            "footer" => Some(Tag::FOOTER),
            "form" => Some(Tag::FORM),
            "frame" => Some(Tag::FRAME),
            "frameset" => Some(Tag::FRAMESET),
            "h1" => Some(Tag::H1),
            "h2" => Some(Tag::H2),
            "h3" => Some(Tag::H3),
            "h4" => Some(Tag::H4),
            "h5" => Some(Tag::H5),
            "h6" => Some(Tag::H6),
            "head" => Some(Tag::HEAD),
            "header" => Some(Tag::HEADER),
            "hgroup" => Some(Tag::HGROUP),
            "hr" => Some(Tag::HR),
            "html" => Some(Tag::HTML),
            "i" => Some(Tag::I),
            "iframe" => Some(Tag::IFRAME),
            "img" => Some(Tag::IMG),
            "input" => Some(Tag::INPUT),
            "ins" => Some(Tag::INS),
            "isindex" => Some(Tag::ISINDEX),
            "kbd" => Some(Tag::KBD),
            "keygen" => Some(Tag::KEYGEN),
            "label" => Some(Tag::LABEL),
            "legend" => Some(Tag::LEGEND),
            "li" => Some(Tag::LI),
            "link" => Some(Tag::LINK),
            "listing" => Some(Tag::LISTING),
            "main" => Some(Tag::MAIN),
            "map" => Some(Tag::MAP),
            "mark" => Some(Tag::MARK),
            "marquee" => Some(Tag::MARQUEE),
            "menu" => Some(Tag::MENU),
            "menuitem" => Some(Tag::MENUITEM),
            "meta" => Some(Tag::META),
            "meter" => Some(Tag::METER),
            "nav" => Some(Tag::NAV),
            "nobr" => Some(Tag::NOBR),
            "noframes" => Some(Tag::NOFRAMES),
            "noscript" => Some(Tag::NOSCRIPT),
            "object" => Some(Tag::OBJECT),
            "ol" => Some(Tag::OL),
            "optgroup" => Some(Tag::OPTGROUP),
            "option" => Some(Tag::OPTION),
            "output" => Some(Tag::OUTPUT),
            "p" => Some(Tag::P),
            "param" => Some(Tag::PARAM),
            "plaintext" => Some(Tag::PLAINTEXT),
            "pre" => Some(Tag::PRE),
            "progress" => Some(Tag::PROGRESS),
            "q" => Some(Tag::Q),
            "rp" => Some(Tag::RP),
            "rt" => Some(Tag::RT),
            "ruby" => Some(Tag::RUBY),
            "s" => Some(Tag::S),
            "samp" => Some(Tag::SAMP),
            "script" => Some(Tag::SCRIPT),
            "section" => Some(Tag::SECTION),
            "select" => Some(Tag::SELECT),
            "shadow" => Some(Tag::SHADOW),
            "small" => Some(Tag::SMALL),
            "source" => Some(Tag::SOURCE),
            "spacer" => Some(Tag::SECTION),
            "span" => Some(Tag::SPAN),
            "strike" => Some(Tag::STRIKE),
            "strong" => Some(Tag::STRONG),
            "style" => Some(Tag::STYLE),
            "sub" => Some(Tag::SUB),
            "summary" => Some(Tag::SUMMARY),
            "sup" => Some(Tag::SUP),
            "table" => Some(Tag::TABLE),
            "tbody" => Some(Tag::TBODY),
            "td" => Some(Tag::TD),
            "template" => Some(Tag::TEMPLATE),
            "textarea" => Some(Tag::TEXTAREA),
            "tfoot" => Some(Tag::TFOOT),
            "th" => Some(Tag::TH),
            "thead" => Some(Tag::THEAD),
            "time" => Some(Tag::TIME),
            "title" => Some(Tag::TITLE),
            "tr" => Some(Tag::TR),
            "track" => Some(Tag::TRACK),
            "tt" => Some(Tag::TT),
            "u" => Some(Tag::U),
            "ul" => Some(Tag::UL),
            "var" => Some(Tag::VAR),
            "video" => Some(Tag::VIDEO),
            "wbr" => Some(Tag::WBR),
            "xmp" => Some(Tag::XMP),

            _ => None,
        }
    }
}
